Catkin-ProjectName: ompl
Version: 0.10.2001910
Release-Tag: 1910

Depends: cmake,
    boost

Description: OMPL is a free sampling-based motion planning library.

Author: Kavraki Lab
Maintainer: Ioan Sucan <isucan@willowgarage.com>
Homepage: http://ompl.kavrakilab.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
