Catkin-ProjectName: ompl
Version: 0.10.2001842
Release-Tag: 1842

Depends: cmake,
    libgtest-dev,
    boost

Description: OMPL is a free sampling-based motion planning library.

Author: Kavraki Lab
Maintainer: Ioan Sucan <isucan@willowgarage.com>
Homepage: http://ompl.kavrakilab.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
