Catkin-ProjectName: ompl
Version: 0.9.5

Depends: cmake,
    libgtest-dev,
    boost

Description: OMPL is a sampling-based motion planning library

Author: Kavraki Lab
Maintainer: Ioan Sucan <isucan@willowgarage.com>
Homepage: http://ompl.kavrakilab.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
